### ISSUE TITLE
v209 not on bosh.io?

### ISSUE THREAD

**Issue by will-gant** [cloudfoundry-community/logsearch-boshrelease#118]
Hi

We're pipelining a deployment of Logsearch and Logsearch-for-Cloudfoundry. Yesterday morning our pipeline picked up a new version of the latter (v207) from bosh.io, which is apparently only compatible with v209 of Logsearch. That was published in GitHub at about the same time, but hasn't appeared on bosh.io yet. As such, our pipeline job is failing, as it's still using v208 of Logsearch.

Just wondering if v209 of Logsearch is expected to make it on to bosh.io sometime soon?

Thanks!

**Comment by Infra-Red** [comment]
Hi @bruxelles86, it should be picked up automatically when new release is available on Github. We don’t do any additional steps to make it available on bosh.io. I will check what is wrong with integration, but at the same time you can use release tarball from releases page to proceed with v209.0.0 deployment.

**Comment by will-gant** [comment]
Thanks. We prefer using bosh.io, but will probably switch over temporarily.

**Comment by xyloman** [comment]
We are having the same issue.  The new version of logsearch-for-cloudfoundry is getting picked up via our concourse pipeline using the bosh-io-release concourse resource, which is creating an issue with incompatibilities. 

```
- name: logsearch-boshrelease
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/logsearch-boshrelease

- name: logsearch-for-cloudfoundry
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/logsearch-for-cloudfoundry
```
