### ISSUE TITLE
Suggestion to allow for conditional ingestor outputs

### ISSUE THREAD

**Issue by jblackman** [cloudfoundry-community/logsearch-boshrelease#185]
Logstash allows us to wrap an output (or input) in a condition block. Could I propose adding a `condition:` key to the `logstash_parser.outputs` array? For example:

```yaml
instance_groups:
- name: ingestor
  jobs:
  - name: ingestor_syslog
    properties:
      logstash_parser:
        outputs:
        - plugin: foo
          options:
            key: "value"
          condition:  '[syslog_program] == "gorouter"'
```

and this would produce output config like:

```
outputs {
  if [syslog_program] == "gorouter" {
    foo {
      key => "value"
    }
  }
}
```

Happy to create a PR for this. I just want to get some feedback if this is an appropriate way to make the change. An alternative would be to create a `output_overrides` parameter to allow complete customisability, similar to `filter_overrides`.

**Comment by jblackman** [comment]
It could also be extended to `else` blocks with a minor change:

```yaml
outputs:
- plugin: foo
  options:
    key: "value"
  condition:  'if [syslog_program] == "gorouter"'
- plugin: bar
  options:
    key: "value"
  condition:  'else'
```

which would produce:

```
outputs {
  if [syslog_program] == "gorouter" {
    foo {
      key => "value"
    }
  }
  else {
    bar {
      key => "value"
    }
  }
}
```
