### ISSUE TITLE
Smoke tests query all indices

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry-community/logsearch-boshrelease#64]
The smoke tests currently query all indices: https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/jobs/smoke_tests/templates/run.sh#L24. If this query hits more than `action.search.shard_count.limit` shards, which defaults to 1000, then the query will fail. This means that smoke tests fail once a logsearch deployment grows to over 1000 shards, unless the shard count limit is increased--which operators might not want to do, for performance reasons.

The smoke tests should expose some method for restricting queries to one or a few indices. What do you think about adding a parameter that the smoke test script evaluates in bash, like this:

```yaml
properties:
  smoke_tests.indices:
    example: "logs-*-$(date +%Y-%m-%d -d yesterday),logs-*-$(date +%Y-%m-%d)"
```

cc @cnelson
